In [1]:
import numpy as np

In [2]:
# 3d Array

a = np.array([[[2,3,4],
           [1,2,3],
           [4,5,6]],

           [[2,3,4],
           [1,2,3],
           [4,5,6]],

           [[2,3,4],
           [1,2,3],
           [4,5,6]]])

In [3]:
print(a)

[[[2 3 4]
  [1 2 3]
  [4 5 6]]

 [[2 3 4]
  [1 2 3]
  [4 5 6]]

 [[2 3 4]
  [1 2 3]
  [4 5 6]]]


In [4]:
a.shape

(3, 3, 3)

In [9]:
b = np.array([[[2,3,4,5,6],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [4,5,6,7,8]],

           [[2,3,4,5,6],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [4,5,6,7,8,]],

           [[2,3,4,5,6],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [1,2,3,4,5],
           [4,5,6,7,8]]])

In [10]:
print(b)

[[[2 3 4 5 6]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [4 5 6 7 8]]

 [[2 3 4 5 6]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [4 5 6 7 8]]

 [[2 3 4 5 6]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [4 5 6 7 8]]]


In [13]:
b.shape

(3, 5, 5)

In [17]:
data = np.random.randint(1,50,(3,5,5))

In [19]:
print(data)
data.shape

[[[13 26 46 36 48]
  [28  3 33  4 38]
  [42 45 29 49  6]
  [11 25  3 17 43]
  [14 46 34 25 33]]

 [[ 1 37 48 30  5]
  [14 21  4 15 33]
  [13 16 13 48 48]
  [48 10 22 33 13]
  [ 8 25 41 48 26]]

 [[ 8 26 25 20 40]
  [ 5 25 17 10 16]
  [41 44  7  6  3]
  [42 21 24 30 11]
  [27 16 28  6 35]]]


(3, 5, 5)

In [20]:
data1 = np.random.randint(1,100,(4,4,4))

In [22]:
print(data1)
data1.shape

[[[90 46  4  9]
  [23  4 63 36]
  [98 18  8 75]
  [23 89 72 76]]

 [[88 61 28  7]
  [55 51 32 19]
  [44 70 89 85]
  [54 62 78 74]]

 [[19 22 42  8]
  [98 44 85 53]
  [26 56 81 49]
  [35 57 67 38]]

 [[ 5 33  2 51]
  [ 6 16 96 19]
  [75 59 13 61]
  [12 55 50  2]]]


(4, 4, 4)